### ISSUE TITLE
Allow WorkingDirectory to resolve Environment Variables

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/handlers.CommandLine.net#29]
Example: `WorkingDirectory: %temp%`

```yaml
Actions:
- Name: Action001
  Handler:
    Type: Synapse.Handlers.CommandLine:CommandHandler
    Config:
      Values:
        WorkingDirectory: %temp%
        Command: powershell.exe
        TimeoutMills: 5000
        TimeoutStatus: Failed
```
